// ============================================================
// FILE: models/medicine_model.dart
// ============================================================

class Medicine {
  final String id;
  final String name;
  final String brand;
  final String description;
  final double price;
  final double mrp;
  final int discountPercent;
  final String imageUrl;
  final String category;
  final String composition;
  final String manufacturer;
  final bool requiresPrescription;
  final bool inStock;
  final int stockCount;
  final double rating;
  final int reviewCount;
  final List<String> uses;
  final List<String> sideEffects;
  final String dosage;
  final String packSize;

  Medicine({
    required this.id,
    required this.name,
    required this.brand,
    required this.description,
    required this.price,
    required this.mrp,
    required this.discountPercent,
    required this.imageUrl,
    required this.category,
    required this.composition,
    required this.manufacturer,
    required this.requiresPrescription,
    required this.inStock,
    required this.stockCount,
    required this.rating,
    required this.reviewCount,
    required this.uses,
    required this.sideEffects,
    required this.dosage,
    required this.packSize,
  });

  factory Medicine.fromJson(Map<String, dynamic> json) {
    return Medicine(
      id: json['id'] ?? '',
      name: json['name'] ?? '',
      brand: json['brand'] ?? '',
      description: json['description'] ?? '',
      price: (json['price'] ?? 0).toDouble(),
      mrp: (json['mrp'] ?? 0).toDouble(),
      discountPercent: json['discountPercent'] ?? 0,
      imageUrl: json['imageUrl'] ?? '',
      category: json['category'] ?? '',
      composition: json['composition'] ?? '',
      manufacturer: json['manufacturer'] ?? '',
      requiresPrescription: json['requiresPrescription'] ?? false,
      inStock: json['inStock'] ?? true,
      stockCount: json['stockCount'] ?? 0,
      rating: (json['rating'] ?? 0).toDouble(),
      reviewCount: json['reviewCount'] ?? 0,
      uses: List<String>.from(json['uses'] ?? []),
      sideEffects: List<String>.from(json['sideEffects'] ?? []),
      dosage: json['dosage'] ?? '',
      packSize: json['packSize'] ?? '',
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'brand': brand,
        'description': description,
        'price': price,
        'mrp': mrp,
        'discountPercent': discountPercent,
        'imageUrl': imageUrl,
        'category': category,
        'composition': composition,
        'manufacturer': manufacturer,
        'requiresPrescription': requiresPrescription,
        'inStock': inStock,
        'stockCount': stockCount,
        'rating': rating,
        'reviewCount': reviewCount,
        'uses': uses,
        'sideEffects': sideEffects,
        'dosage': dosage,
        'packSize': packSize,
      };
}

// ============================================================
// Dummy data for testing (replace with API call)
// ============================================================
List<Medicine> getDummyMedicines() {
  return [
    Medicine(
      id: 'm1',
      name: 'Paracetamol 500mg',
      brand: 'Calpol',
      description: 'Used for fever and mild to moderate pain relief.',
      price: 18.0,
      mrp: 22.0,
      discountPercent: 18,
      imageUrl: 'https://via.placeholder.com/200x200?text=Paracetamol',
      category: 'Pain Relief',
      composition: 'Paracetamol 500mg',
      manufacturer: 'GlaxoSmithKline',
      requiresPrescription: false,
      inStock: true,
      stockCount: 100,
      rating: 4.5,
      reviewCount: 2340,
      uses: ['Fever', 'Headache', 'Body Pain'],
      sideEffects: ['Nausea (rare)', 'Allergic reaction (rare)'],
      dosage: '1-2 tablets every 4-6 hours',
      packSize: 'Strip of 15 tablets',
    ),
    Medicine(
      id: 'm2',
      name: 'Azithromycin 500mg',
      brand: 'Azithral',
      description: 'Antibiotic for bacterial infections.',
      price: 95.0,
      mrp: 110.0,
      discountPercent: 14,
      imageUrl: 'https://via.placeholder.com/200x200?text=Azithromycin',
      category: 'Antibiotics',
      composition: 'Azithromycin 500mg',
      manufacturer: 'Alembic Pharma',
      requiresPrescription: true,
      inStock: true,
      stockCount: 50,
      rating: 4.3,
      reviewCount: 892,
      uses: ['Respiratory infections', 'Skin infections', 'Ear infections'],
      sideEffects: ['Nausea', 'Diarrhea', 'Stomach pain'],
      dosage: '1 tablet once daily for 3-5 days',
      packSize: 'Strip of 6 tablets',
    ),
    Medicine(
      id: 'm3',
      name: 'Cetirizine 10mg',
      brand: 'Cetzine',
      description: 'Antihistamine for allergies and hay fever.',
      price: 28.0,
      mrp: 35.0,
      discountPercent: 20,
      imageUrl: 'https://via.placeholder.com/200x200?text=Cetirizine',
      category: 'Allergy',
      composition: 'Cetirizine Hydrochloride 10mg',
      manufacturer: 'Sun Pharma',
      requiresPrescription: false,
      inStock: true,
      stockCount: 200,
      rating: 4.6,
      reviewCount: 1230,
      uses: ['Allergic rhinitis', 'Urticaria', 'Sneezing', 'Runny nose'],
      sideEffects: ['Drowsiness', 'Dry mouth', 'Headache'],
      dosage: '1 tablet once daily',
      packSize: 'Strip of 10 tablets',
    ),
    Medicine(
      id: 'm4',
      name: 'Omeprazole 20mg',
      brand: 'Omez',
      description: 'Proton pump inhibitor for acidity and ulcers.',
      price: 55.0,
      mrp: 65.0,
      discountPercent: 15,
      imageUrl: 'https://via.placeholder.com/200x200?text=Omeprazole',
      category: 'Gastro',
      composition: 'Omeprazole 20mg',
      manufacturer: 'Dr. Reddys',
      requiresPrescription: false,
      inStock: true,
      stockCount: 80,
      rating: 4.4,
      reviewCount: 1560,
      uses: ['Acidity', 'GERD', 'Stomach ulcers', 'Heartburn'],
      sideEffects: ['Headache', 'Diarrhea', 'Nausea'],
      dosage: '1 capsule before meal, once daily',
      packSize: 'Strip of 10 capsules',
    ),
    Medicine(
      id: 'm5',
      name: 'Vitamin D3 60000 IU',
      brand: 'D-Rise',
      description: 'Vitamin D3 supplement for deficiency.',
      price: 75.0,
      mrp: 90.0,
      discountPercent: 17,
      imageUrl: 'https://via.placeholder.com/200x200?text=Vitamin+D3',
      category: 'Vitamins',
      composition: 'Cholecalciferol 60000 IU',
      manufacturer: 'USV Pvt Ltd',
      requiresPrescription: false,
      inStock: true,
      stockCount: 150,
      rating: 4.7,
      reviewCount: 3420,
      uses: ['Vitamin D deficiency', 'Bone health', 'Immunity'],
      sideEffects: ['Nausea (high dose)', 'Constipation (high dose)'],
      dosage: '1 sachet once weekly or as directed',
      packSize: 'Pack of 4 sachets',
    ),
    Medicine(
      id: 'm6',
      name: 'Metformin 500mg',
      brand: 'Glycomet',
      description: 'Oral antidiabetic for type 2 diabetes management.',
      price: 42.0,
      mrp: 50.0,
      discountPercent: 16,
      imageUrl: 'https://via.placeholder.com/200x200?text=Metformin',
      category: 'Diabetes',
      composition: 'Metformin Hydrochloride 500mg',
      manufacturer: 'USV Pvt Ltd',
      requiresPrescription: true,
      inStock: true,
      stockCount: 60,
      rating: 4.2,
      reviewCount: 780,
      uses: ['Type 2 Diabetes', 'Blood sugar control'],
      sideEffects: ['Nausea', 'Diarrhea', 'Stomach upset'],
      dosage: '1 tablet twice daily with meals',
      packSize: 'Strip of 20 tablets',
    ),
    Medicine(
      id: 'm7',
      name: 'Amoxicillin 500mg',
      brand: 'Mox',
      description: 'Broad-spectrum antibiotic for bacterial infections.',
      price: 68.0,
      mrp: 80.0,
      discountPercent: 15,
      imageUrl: 'https://via.placeholder.com/200x200?text=Amoxicillin',
      category: 'Antibiotics',
      composition: 'Amoxicillin Trihydrate 500mg',
      manufacturer: 'Ranbaxy Labs',
      requiresPrescription: true,
      inStock: false,
      stockCount: 0,
      rating: 4.1,
      reviewCount: 540,
      uses: ['Throat infections', 'Urinary tract infections', 'Skin infections'],
      sideEffects: ['Diarrhea', 'Rash', 'Nausea'],
      dosage: '1 capsule 3 times daily for 5-7 days',
      packSize: 'Strip of 15 capsules',
    ),
    Medicine(
      id: 'm8',
      name: 'Pantoprazole 40mg',
      brand: 'Pan 40',
      description: 'Proton pump inhibitor for acid-related conditions.',
      price: 48.0,
      mrp: 58.0,
      discountPercent: 17,
      imageUrl: 'https://via.placeholder.com/200x200?text=Pantoprazole',
      category: 'Gastro',
      composition: 'Pantoprazole Sodium 40mg',
      manufacturer: 'Alkem Labs',
      requiresPrescription: false,
      inStock: true,
      stockCount: 120,
      rating: 4.5,
      reviewCount: 1890,
      uses: ['Acidity', 'GERD', 'Peptic ulcer', 'Zollinger-Ellison syndrome'],
      sideEffects: ['Headache', 'Diarrhea', 'Flatulence'],
      dosage: '1 tablet before breakfast daily',
      packSize: 'Strip of 15 tablets',
    ),
  ];
}
